### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by AkiMiyazawa** [CS130-W20/team-B10#1]
## User Story
As a user, I would like to login and signup so that I can have my preferences stored and access the web app to generate itineraries

## Detailed Description
The login and signup page should allow users to create accounts get the information stored in the database

## Acceptance Criteria
- [x] Given the user is logged in, then proceed to the main page
- [x] Given the user is logged out, then the page asks the user to log in or sign up 
- [x] Given the user is new, then ask the user to sign up

**Comment by zeroblackalpha** [comment]
Completed in e158985
