### ISSUE TITLE
User Preferences Input

### ISSUE THREAD

**Issue by jsicheng** [CS130-W20/team-B10#29]
## User Story
As a user, I would like to input my preferences so that the website will receive my preferences.

## Detailed Description
Allow users to click/select bubbly in options to select their preferences

## Acceptance Criteria
- [x] Given preference options are displayed then allow users to click their preferred choice bubble.

**Comment by AkiMiyazawa** [comment]
the survey contains multiple-choice questions that allow a user to select preferences.
