### ISSUE TITLE
Go Back/Previous

### ISSUE THREAD

**Issue by jsicheng** [CS130-W20/team-B10#31]
## User Story
As a user, I would like be able to go back and change preferences so that I do not have to start all over again when making a mistake in choosing preferences.

## Detailed Description
Create a 'previous' button in itinerary creation so that the user can go back a change their preferences.

## Acceptance Criteria
- [x] Given the user makes a mistake in selection, then allow them to go back and select their preferred option.

**Comment by AkiMiyazawa** [comment]
next and previous button successfully implemented to change preferences
