### ISSUE TITLE
Preferences Survey Progress Bar

### ISSUE THREAD

**Issue by jsicheng** [CS130-W20/team-B10#32]
## User Story
As a user, I would like to see how much of the user preference survey is left so that I know what to expect and do not get impatient.

## Detailed Description
Implement a progress bar showing how many survey are done out of how many pages total.

## Acceptance Criteria
- [x] Given the user starts the survey, then display how many pages are completed out of how many pages total.

**Comment by AkiMiyazawa** [comment]
survey shows progression bar
