### ISSUE TITLE
Create Database Model

### ISSUE THREAD

**Issue by jsicheng** [CS130-W20/team-B10#35]
## User Story
As a developer, I would like to create a consistent database model so that user preferences and itineraries can be stored.

## Detailed Description
Create a database model to store the user preference data as well as the generated itinerary.

## Acceptance Criteria
- [ ] Given user preferences are inputted, then create a database model to store the data.
- [ ] Given the itinerary is generated, then create a database model to store the data.

**Comment by zeroblackalpha** [comment]
Duplicate of #34
